### PR TITLE
Fix typo's in Dutch translation.

### PR DESCRIPTION
**Pull request by ghen2**
From https://bugzilla.zimbra.com/show_bug.cgi?id=109219

### CODE REVIEW

**Review by silentsakky — APPROVED** [review]
Thanks for the contribution !!!

**Comment by silentsakky** [comment]
ZBUG-1120

**Comment by silentsakky** [comment]
Changes moved to https://github.com/Zimbra/zm-web-client/pull/724 for testing and merge

**Comment by silentsakky** [comment]
Fixed is merged in https://github.com/Zimbra/zm-web-client/pull/724

**Comment by ghen2** [comment]
Thanks!

Can you take a look at https://github.com/Zimbra/zm-web-client/pull/599 as well?

**Pull request closed without merging**
