### PR TITLE
Fix wrong sequence of two apostrophes in AjxMessageFormat Formats

### PR DESCRIPTION
**Pull request by zextras-contrib**
Fixing wrong sequences of two apostrophe characters in the French and
Italian localizations.
E.g. «L'ultimo» appearing as «L''ultimo» in a dialog in the Italian web interface.

See pictures for a couple of examples
double-apostrophe-italian
double-apostrophe-french

### CODE REVIEW

**Comment by zextras-contrib** [comment]
@silentsakky No problem.
A question though: are localization resource bundles only in the zm-web-client, zm-mailbox and zm-admin-console repositories? Is there any additional repository hosting localization files?

**Comment by silentsakky** [comment]
Good question :)
There are 14 FOSS repos and 16 Network repos which contains localisation files.
If you have VPN access to zimbra network then you can go to http://wiki.eng.zimbra.com/index.php/Localization_Git to get more information

**Comment by zx-fulvio** [comment]
Pull requests opened for the other two repositories. 👋

**Comment by zx-fulvio** [comment]
@silentsakky : do you see any other file in need of patching when it comes to this specific issue?

**Comment by silentsakky** [comment]
Dropping this PR as this is already covered as part of https://github.com/Zimbra/zm-web-client/pull/134

Thanks for the contribution and healthy discussion on possible approaches to solve this issue, really appreciated !!!

**Pull request closed without merging**
