### PR TITLE
ZCS-15576: On mobile browser, User lands to classic UI instead of modern UI after login

### PR DESCRIPTION
**Pull request by miteshsavani810**

### CODE REVIEW

**Review by silentsakky — APPROVED** [review]

**Review by lavegupta — APPROVED** [review]

**Review by damini-vashishtha — APPROVED** [review]

**Comment by ghen2** [comment]
There's another mobile browser that lands on Classic UI, even with this patch: Samsung Browser:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Safari/537.36`

**Comment by miteshsavani810** [comment]
@ghen2 Can you please tell us on which Samsung device the issue is occurring ?

**Comment by ghen2** [comment]
Any older Samsung Galaxy device with its default Samsung browser, eg. this was on a Galaxy Tab S5e.

**Comment by ghen2** [comment]
The problem seems to be that they do not always have "Android" in their useragent string.
These are the top-10 most popular SamsungBrowser clients in our access logs:

- Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Mobile Safari/537.36
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Safari/537.36
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Safari/537.36
- Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/117.0.0.0 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/25.0 Chrome/121.0.0.0 Safari/537.36
- Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Safari/537.36
- Mozilla/5.0 (Linux; Android 7.1.1; SAMSUNG SM-T550) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/21.0 Chrome/110.0.5481.154 Safari/537.36
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/24.0 Chrome/117.0.0.0 Safari/537.36
- Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/21.0 Chrome/110.0.5481.154 Safari/537.36

**Comment by miteshsavani810** [comment]
@ghen2 
This issue(ZCS-15576) has been reported as regression issue because on zimbra 10 server, all mobile browser users sent to the classic client when zimbraPrefClientType is advanced.

The device that includes the following user agent is also experiencing issues with the Zimbra 9 server. 
We have filed a separate bug to handle the device that includes the user agent shown below.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Safari/537.36` and other user agent which doesn't contains "Android".

**Pull request merged**
