### PR TITLE
Fix: https://bugzilla.zimbra.com/show_bug.cgi?id=106104

### PR DESCRIPTION
**Pull request by barrydegraaff**
Fix: https://bugzilla.zimbra.com/show_bug.cgi?id=106104

### CODE REVIEW

**Comment by barrydegraaff** [comment]
That seems to work OK.

**Comment by barrydegraaff** [comment]
YES, I accept the CA at https://gist.github.com/syncosource/721a9a0651f0e55d7cfc7059ceaf2b20

**Comment by Prashantsurana** [comment]
@barrydegraaff  can you please accept
https://cla-assistant.io/Zimbra/zm-web-client?pullRequest=1

**Comment by Prashantsurana** [comment]
@barrydegraaff can you please accept ?
https://cla-assistant.io/Zimbra/zm-web-client?pullRequest=1

**Comment by barrydegraaff** [comment]
@Prashantsurana done

**Pull request merged**
