### PR TITLE
Bugzilla 98570 - Fix for DST

### PR DESCRIPTION
**Pull request by bud-mo**
Please refer to the conversation located at https://bugzilla.zimbra.com/show_bug.cgi?id=98570

I re-propose the fix.

### CODE REVIEW

**Comment by bud-mo** [comment]
@Prashantsurana please can You take a look at this fix?

**Comment by barrydegraaff** [comment]
@Prashantsurana this one seems to be stuck, perhaps can we assign reviewers now?

**Comment by Prashantsurana** [comment]
@shardool-gore and @dajay0 can you please make sure team reviews, test and merge.
Please schedule this is upcoming 8.8.15  patches as well.

**Comment by silentsakky** [comment]
> @shardool-gore and @dajay0 can you please make sure team reviews, test and merge.
> Please schedule this is upcoming 8.8.15 patches as well.

Have created ZCS-7524 to track external PRs and planned to be completed in next sprint

**Comment by silentsakky** [comment]
Merged in https://github.com/Zimbra/zm-web-client/pull/520

**Pull request closed without merging**
